# frozen_string_literal: true

module RubyUIConverter
  # Represents a single .erb file and knows how to render its .rb equivalent.
  class Template
    attr_reader :path, :root, :config

    def initialize(path:, root:, config:)
      @path = path
      @root = root.to_s
      @config = config
    end

    def source
      @source ||= File.read(path)
    end

    def filename
      File.basename(path)
    end

    # "index.html.erb" -> "index"; "_form.html.erb" -> "_form"
    def basename
      filename.split(".").first
    end

    def partial?
      filename.start_with?("_")
    end

    def rel_path
      expanded = File.expand_path(path)
      base = File.expand_path(root)
      expanded.delete_prefix(base).sub(%r{\A/}, "")
    end

    def dir_rel
      dir = File.dirname(rel_path)
      dir == "." ? "" : dir
    end

    def class_name
      Naming.class_name(basename)
    end

    def namespace_parts
      Naming.namespace_parts(dir_rel, config.base_namespace)
    end

    def full_const
      (namespace_parts + [class_name]).join("::")
    end

    def output_filename
      "#{basename.sub(/\A_/, "")}.rb"
    end

    def output_path
      target_dir =
        if config.output_root
          File.join(config.output_root, dir_rel)
        else
          File.dirname(File.expand_path(path))
        end

      File.join(target_dir, output_filename)
    end

    def tree
      @tree ||= Parser.new(source).parse
    end

    def locals
      @locals ||= partial? ? LocalsDetector.new(tree).locals : []
    end

    # Top-level views read controller instance variables (`@products`); partials
    # take their data as bare locals instead.
    def ivars
      @ivars ||= partial? ? [] : LocalsDetector.new(tree).ivars
    end

    # Keyword arguments the generated initializer/props expose: bare locals for
    # partials (referenced through attr_readers), controller ivars for top-level
    # views (referenced directly as @ivars).
    def init_args
      partial? ? locals : ivars
    end

    def render
      builder = CodeBuilder.new(indent: config.indent)
      builder.line("# frozen_string_literal: true")
      builder.line
      builder.line("# Auto-generated by ruby_ui_converter")
      builder.line("# Source: #{rel_path}")
      builder.line

      namespace_parts.each do |segment|
        builder.line("module #{segment}")
        builder.indent
      end

      builder.line("class #{class_name} < #{config.base_class}")
      builder.indent

      emit_initializer(builder)

      builder.line("def #{config.template_method}")
      builder.indent
      Transformer.new(config: config, template: self).emit(tree, builder)
      builder.dedent
      builder.line("end")

      emit_readers(builder)

      builder.dedent
      builder.line("end")

      namespace_parts.each do
        builder.dedent
        builder.line("end")
      end

      builder.to_s
    end

    private

    def emit_initializer(builder)
      return emit_props(builder) if config.literal?
      return if init_args.empty?

      args = init_args.map { |name| "#{name}: nil" }.join(", ")
      builder.line("def initialize(#{args})")
      builder.indent
      init_args.each { |name| builder.line("@#{name} = #{name}") }
      builder.dedent
      builder.line("end")
      builder.line
    end

    # Literal::Properties props instead of initialize/attr_reader. The local
    # matching the partial's name gets an inferred model type; the rest stay
    # permissive (_Any? accepts anything, including nil).
    def emit_props(builder)
      return if init_args.empty?

      init_args.each { |name| builder.line("prop :#{name}, #{prop_type(name)}") }
      builder.line
    end

    def prop_type(local)
      if local == basename.sub(/\A_/, "")
        "_Nilable(#{Naming.camelize(local)})"
      else
        "_Any?"
      end
    end

    def emit_readers(builder)
      return unless partial? && locals.any?
      return if config.literal? # props set ivars; the body uses @locals

      builder.line
      builder.line("private")
      builder.line
      builder.line("attr_reader #{locals.map { |local| ":#{local}" }.join(", ")}")
    end
  end
end
